### ISSUE TITLE
Unit 5 Homework

### ISSUE THREAD

**Issue by AlexFedosenko** [milashanna/Java#2]
Есть 2 замечания:
1. Пожалуйста, вынеси логику в отдельные методы;
2. Мне кажется, в задаче мин/макс самое важное -- обработка краевых случаев. В особенности меня интересует, если на вход подать пустой массив. Логика нахождения минимума, например, вернет 0. И если массив будет состоять из нулей, ответ будет тем же самым. Правильно ли это?

**Comment by AlexFedosenko** [comment]
Второй случай пока снимается. Точнее переносится на следующий модуль. Но первое замечание было бы хорошо исправить. Пожалуйста

**Comment by milashanna** [comment]
Перенесла. Так подойдет или еще что-то подправить?

**Comment by AlexFedosenko** [comment]
Можешь, пожалуйста, разделить поиск минимума и максимума. 
Предполагается 2 метода, на вход каждого приходит массив. Сам метод возвращает найденное значение.
Спасибо

**Comment by milashanna** [comment]
Исправила. Посмотри еще раз, пожалуйста

**Comment by AlexFedosenko** [comment]
Теперь все отлично.
Молодец=)
